// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for ios - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCqD_zgbbR65556CLQOdFzuWhVwALhyj2A',
    appId: '1:928033390839:web:100c58e2bc9e9197ffd3f2',
    messagingSenderId: '928033390839',
    projectId: 'webtoon-b9373',
    authDomain: 'webtoon-b9373.firebaseapp.com',
    storageBucket: 'webtoon-b9373.appspot.com',
    measurementId: 'G-MR5XV36PVM',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyARnzNXRZNrPkUXooPGHiPvLYE2ZEMZzU0',
    appId: '1:928033390839:android:8d7c8d180d9b6d11ffd3f2',
    messagingSenderId: '928033390839',
    projectId: 'webtoon-b9373',
    storageBucket: 'webtoon-b9373.appspot.com',
  );
}
